version: '3'

services:
  web:
    build: .
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    build: .
    command: celery worker --app=vocabulary_api --loglevel=info
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      - web
      - redis

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
